### ISSUE TITLE
Create a program that asks the user their name then greets them

### ISSUE THREAD

**Issue by lcabrini** [mamashe/sheila-java-learning#13]
Write a program, called greet, that asks the user their name and greets them. If the user enters an empty name, the program should instead print "Coward!"

Here follows sample output.

```
$ java Greet
Hi there. What is your name? Lorenzo
Oh hello, Lorenzo, welcome to Java!

$ java Greet
Hi there. What is your name? Sheila
Oh hello, Sheila, welcome to Java!

$ java Greet
Hi there. What is your name?
Coward!
```

**Comment by mamashe** [comment]
I compiled the code and had some errors on the if statement. i guess Scanner does not support boolean. but did not know what to use in place of that. please assist me. i tried googling but i had hard time figuring it out.

**Comment by lcabrini** [comment]
You have created a Scanner object, but you then need to read from it. What you probably meant was.

```
Scanner scanner = new Scanner(System.in);
String name = scanner.nextLine();
```

The first line creates the scanner, and the next line assigns the next line of input to a string.
