### ISSUE TITLE
Write a program that prints out your Akan name

### ISSUE THREAD

**Issue by lcabrini** [mamashe/sheila-java-learning#16]
Write a program that asks the user to enter their gender and the day of the week they were born. The program should then print out your Akan name. You can choose which Akan tribe's names you want to use. Or, print out the variants for Asante, Fante, etc.

The program must validate all input. That is, it should make sure you enter a valid gender and a valid weekday. 

Place the program in a folder called akan-name.

**Comment by mamashe** [comment]
I tried to get this done for some days now but to no avail. am actually sad i wasn't able to do it. i used different approach to achieve but did not know how to apply them. I thought of using Arrays but later I used methods and nested elseif statement. i also thought of using java.util.NoSuchElementException, for the validation but couldnt use it. please assist me.

**Comment by lcabrini** [comment]
That's okay. Don't get sad. I'll write up a little on the wiki on a method you can use. Give me a little bit of time.

**Comment by mamashe** [comment]
i have been able to practice the Akan name codes you took me through on monday. but what i observe is the input validation is case sensitive. for instance, when a user type tuesday instead of Tuesday, it print an error. is there a way to include case sensitive to the code to accept the day or gender in small caps or big caps. it doesnt make sense to a user when he input monday which is a valid day but the app print an error message.

**Comment by lcabrini** [comment]
The java String class has two methods that could be useful for this: toUpperCase() and toLowerCase(). Choose one. I prefer lower-casing becasue I don't like SHOUTING. :)

As an example, take this line from your code.

```
String input = console.readLine("Enter A Day Of The Week: ");
```

All you have to do to make it handle any case is:

```
String input = console.readLine("Enter A Day Of The Week: ").toLowerCase();
```

But you have to be ready to explain how this line of code works to me.

In noticed that you are using the Console class instead of the Scanner class. It is good that you practice using different classes, that way you learn more about the available classes in the Java class library. But, if you feel most comfortable with Scanner, go ahead and use it. It is the most "modern" of the input methods for Java, after all.
