### ISSUE TITLE
triangle: use double for width, height and area.

### ISSUE THREAD

**Issue by lcabrini** [mamashe/sheila-java-learning#25]
I think it is better to use double as a data type for the input variables width and height as well as for the area.

**Comment by mamashe** [comment]
Hi Lorenzo, i used double for the width, height and area of the triangle but after compiling and running the program, it throw java.util.illegalFormatConversion Exception. java.lang.Double.

**Comment by lcabrini** [comment]
Could you commit the code? Don't add closes #25 to the commit message, but rather Refs #25.

**Comment by mamashe** [comment]
I have committed the code. I am also reading up from the API doc to see if i can use the try catch you thought me yesterday.

**Comment by lcabrini** [comment]
The problem is in System.out.printf. You have used %d as a placeholder. But %d is used for integers. You need %f instead. To limit the amount of digits after the decimal point you may want to try something like %.2f.
