### ISSUE TITLE
Create a program that prints out the command-line arguments

### ISSUE THREAD

**Issue by lcabrini** [mamashe/sheila-java-learning#3]
Write a program that prints the number of command-line arguments that it was given and then lists them. The program should go into a folder called args.

The following shows how the program should work. When run, your program must produce this output.

```
$ java Args abc def
Got 2 command-line arguments
1. abc
2. def

$ java Args 1 2 3 "hello world" i am hungry
Got 7 command-line arguments
1. 1
2. 2
3. 3
4. hello world
5. i
6. am
7. hungry

$ java Args test
Got 1 command-line argument
1. test
```

   $ java Args
   No command-line arguments.

**Comment by mamashe** [comment]
I have no idea of java command line arguments

**Comment by lcabrini** [comment]
If you look at the main method in a typical java program:

```
public static void main(String[] args)
```

You see that the method takes a parameter called args, which is a String array, right? Well that will hold the command-line arguments.
