### ISSUE TITLE
create app: random-numbers

### ISSUE THREAD

**Issue by lcabrini** [mamashe/sheila-java-learning#34]
Read up the API documentation of java.util.Random. Then write an application that prints out 10 random numbers between 0 and 100. Place the application in a folder called random-numbers.

**Comment by mamashe** [comment]
I have come up with two different solution on the random application. App.java is exactly what you want me to achieve in this issue but when reading online i came with another approach and i thought of sharing that with you which is Sample.java. Please let me know the benefit of Random in java apart from printing out numbers randomly.

**Comment by lcabrini** [comment]
The Random class is used to generate random numbers. These can be printed, but there is much else that you can do with random numbers.
1. They are used in games to add an element of uncertainty
2. They are used in cryptography
3. They are used in simulations, for example climate simulations
4. If you've ever used a music player with a "shuffle" feature, that is done using random numbers
5. Many graphical effects, such as "old photo" use random to add variation to the produced images
