### ISSUE TITLE
create a number guessing game.

### ISSUE THREAD

**Issue by lcabrini** [mamashe/sheila-java-learning#39]
This program depends on #34 

In a folder called guess-the-number, create a class Game which generates a random number between 1 and 100. The user is then asked to guess this number. If the user's guess is lower than the secret number, print the message "too low" and ask the user to guess again. If the guess is higher than the secret number, print "too high" and ask the user to guess again.

The game should continue until the user has guessed the correct number. At this point the program should print "You got it!" followed by a messsage indicating how many guesses the user needed to make to win the game.

Create an App class that kicks of a game.

**Comment by mamashe** [comment]
I have achieved this issue but my only concern is users will find it very difficult to win this game
