### ISSUE TITLE
countup: fix indentation

### ISSUE THREAD

**Issue by lcabrini** [mamashe/sheila-java-learning#6]
Just a few stylistic changes to countup. First, in Java it is conventional to use 4-space indents. You should be able to set that in your text editors configuration.

Second, make sure that all blocks are properly indented. This becomes important when you end up with more levels of indentation, so let's do it right from the start. The code in the method should also be indented. Here is a version that follows these conventions.

Third, conventionally, the name of the argument passed to main is args, not arg. That is to indicate that it is an array that takes multiple values.

```
public class CountUp {
    public static void main(String[] args) {
        for (int i = 1; i <= 10; i++) {
            System.out.println(i);
        }
    }
}
```

**Comment by mamashe** [comment]
Thanks and well noted

**Comment by lcabrini** [comment]
You're welcome. :)

**Comment by lcabrini** [comment]
By the way, you could also use the label Bug instead of enhancement. If we agree that enhancement should be used for new programs or new features, and bug is meant for things that need to be fixed. But I'll let you decide on that one. Just keep in mind that you should implement a system that makes it easier for you when you need to search/filter.
